/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class ACompStm extends PStm
{
    private PCompoundstm _compoundstm_;

    public ACompStm()
    {
        // Constructor
    }

    public ACompStm(
        @SuppressWarnings("hiding") PCompoundstm _compoundstm_)
    {
        // Constructor
        setCompoundstm(_compoundstm_);

    }

    @Override
    public Object clone()
    {
        return new ACompStm(
            cloneNode(this._compoundstm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompStm(this);
    }

    public PCompoundstm getCompoundstm()
    {
        return this._compoundstm_;
    }

    public void setCompoundstm(PCompoundstm node)
    {
        if(this._compoundstm_ != null)
        {
            this._compoundstm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._compoundstm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._compoundstm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._compoundstm_ == child)
        {
            this._compoundstm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._compoundstm_ == oldChild)
        {
            setCompoundstm((PCompoundstm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
