/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyStm extends PStm
{

    public AEmptyStm()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyStm();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyStm(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
