/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class AExitStm extends PStm
{
    private PDocument _document_;

    public AExitStm()
    {
        // Constructor
    }

    public AExitStm(
        @SuppressWarnings("hiding") PDocument _document_)
    {
        // Constructor
        setDocument(_document_);

    }

    @Override
    public Object clone()
    {
        return new AExitStm(
            cloneNode(this._document_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExitStm(this);
    }

    public PDocument getDocument()
    {
        return this._document_;
    }

    public void setDocument(PDocument node)
    {
        if(this._document_ != null)
        {
            this._document_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._document_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._document_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._document_ == child)
        {
            this._document_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._document_ == oldChild)
        {
            setDocument((PDocument) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
