/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

@SuppressWarnings("nls")
public final class AHtml extends PHtml
{
    private TIdentifier _identifier_;
    private final LinkedList<PHtmlbody> _htmlbody_ = new LinkedList<PHtmlbody>();

    public AHtml()
    {
        // Constructor
    }

    public AHtml(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _htmlbody_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setHtmlbody(_htmlbody_);

    }

    @Override
    public Object clone()
    {
        return new AHtml(
            cloneNode(this._identifier_),
            cloneList(this._htmlbody_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHtml(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PHtmlbody> getHtmlbody()
    {
        return this._htmlbody_;
    }

    public void setHtmlbody(List<?> list)
    {
        for(PHtmlbody e : this._htmlbody_)
        {
            e.parent(null);
        }
        this._htmlbody_.clear();

        for(Object obj_e : list)
        {
            PHtmlbody e = (PHtmlbody) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._htmlbody_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._htmlbody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._htmlbody_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PHtmlbody> i = this._htmlbody_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PHtmlbody) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
