/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class ANameInputattr extends PInputattr
{
    private TName _name_;
    private PAttr _attr_;

    public ANameInputattr()
    {
        // Constructor
    }

    public ANameInputattr(
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") PAttr _attr_)
    {
        // Constructor
        setName(_name_);

        setAttr(_attr_);

    }

    @Override
    public Object clone()
    {
        return new ANameInputattr(
            cloneNode(this._name_),
            cloneNode(this._attr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANameInputattr(this);
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PAttr getAttr()
    {
        return this._attr_;
    }

    public void setAttr(PAttr node)
    {
        if(this._attr_ != null)
        {
            this._attr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._attr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._attr_ == child)
        {
            this._attr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._attr_ == oldChild)
        {
            setAttr((PAttr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
