/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

@SuppressWarnings("nls")
public final class APlugs extends PPlugs
{
    private final LinkedList<PPlug> _plug_ = new LinkedList<PPlug>();

    public APlugs()
    {
        // Constructor
    }

    public APlugs(
        @SuppressWarnings("hiding") List<?> _plug_)
    {
        // Constructor
        setPlug(_plug_);

    }

    @Override
    public Object clone()
    {
        return new APlugs(
            cloneList(this._plug_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPlugs(this);
    }

    public LinkedList<PPlug> getPlug()
    {
        return this._plug_;
    }

    public void setPlug(List<?> list)
    {
        for(PPlug e : this._plug_)
        {
            e.parent(null);
        }
        this._plug_.clear();

        for(Object obj_e : list)
        {
            PPlug e = (PPlug) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._plug_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._plug_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._plug_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PPlug> i = this._plug_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPlug) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
