/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class APosintIntconst extends PIntconst
{
    private TPosIntconst _posIntconst_;

    public APosintIntconst()
    {
        // Constructor
    }

    public APosintIntconst(
        @SuppressWarnings("hiding") TPosIntconst _posIntconst_)
    {
        // Constructor
        setPosIntconst(_posIntconst_);

    }

    @Override
    public Object clone()
    {
        return new APosintIntconst(
            cloneNode(this._posIntconst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPosintIntconst(this);
    }

    public TPosIntconst getPosIntconst()
    {
        return this._posIntconst_;
    }

    public void setPosIntconst(TPosIntconst node)
    {
        if(this._posIntconst_ != null)
        {
            this._posIntconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._posIntconst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._posIntconst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._posIntconst_ == child)
        {
            this._posIntconst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._posIntconst_ == oldChild)
        {
            setPosIntconst((TPosIntconst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
