/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class ARadiotypeInputtype extends PInputtype
{
    private TRadio _radio_;

    public ARadiotypeInputtype()
    {
        // Constructor
    }

    public ARadiotypeInputtype(
        @SuppressWarnings("hiding") TRadio _radio_)
    {
        // Constructor
        setRadio(_radio_);

    }

    @Override
    public Object clone()
    {
        return new ARadiotypeInputtype(
            cloneNode(this._radio_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARadiotypeInputtype(this);
    }

    public TRadio getRadio()
    {
        return this._radio_;
    }

    public void setRadio(TRadio node)
    {
        if(this._radio_ != null)
        {
            this._radio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._radio_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._radio_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._radio_ == child)
        {
            this._radio_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._radio_ == oldChild)
        {
            setRadio((TRadio) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
