/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

@SuppressWarnings("nls")
public final class AReceive extends PReceive
{
    private final LinkedList<PInput> _input_ = new LinkedList<PInput>();

    public AReceive()
    {
        // Constructor
    }

    public AReceive(
        @SuppressWarnings("hiding") List<?> _input_)
    {
        // Constructor
        setInput(_input_);

    }

    @Override
    public Object clone()
    {
        return new AReceive(
            cloneList(this._input_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReceive(this);
    }

    public LinkedList<PInput> getInput()
    {
        return this._input_;
    }

    public void setInput(List<?> list)
    {
        for(PInput e : this._input_)
        {
            e.parent(null);
        }
        this._input_.clear();

        for(Object obj_e : list)
        {
            PInput e = (PInput) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._input_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._input_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._input_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PInput> i = this._input_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PInput) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
