/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import java.util.*;
import wig.analysis.*;

@SuppressWarnings("nls")
public final class ATagStartHtmlbody extends PHtmlbody
{
    private TIdentifier _identifier_;
    private final LinkedList<PAttribute> _attribute_ = new LinkedList<PAttribute>();

    public ATagStartHtmlbody()
    {
        // Constructor
    }

    public ATagStartHtmlbody(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _attribute_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setAttribute(_attribute_);

    }

    @Override
    public Object clone()
    {
        return new ATagStartHtmlbody(
            cloneNode(this._identifier_),
            cloneList(this._attribute_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATagStartHtmlbody(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PAttribute> getAttribute()
    {
        return this._attribute_;
    }

    public void setAttribute(List<?> list)
    {
        for(PAttribute e : this._attribute_)
        {
            e.parent(null);
        }
        this._attribute_.clear();

        for(Object obj_e : list)
        {
            PAttribute e = (PAttribute) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._attribute_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._attribute_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._attribute_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PAttribute> i = this._attribute_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAttribute) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
