/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class ATypeInputattr extends PInputattr
{
    private TType _type_;
    private PInputtype _inputtype_;

    public ATypeInputattr()
    {
        // Constructor
    }

    public ATypeInputattr(
        @SuppressWarnings("hiding") TType _type_,
        @SuppressWarnings("hiding") PInputtype _inputtype_)
    {
        // Constructor
        setType(_type_);

        setInputtype(_inputtype_);

    }

    @Override
    public Object clone()
    {
        return new ATypeInputattr(
            cloneNode(this._type_),
            cloneNode(this._inputtype_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATypeInputattr(this);
    }

    public TType getType()
    {
        return this._type_;
    }

    public void setType(TType node)
    {
        if(this._type_ != null)
        {
            this._type_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._type_ = node;
    }

    public PInputtype getInputtype()
    {
        return this._inputtype_;
    }

    public void setInputtype(PInputtype node)
    {
        if(this._inputtype_ != null)
        {
            this._inputtype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inputtype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._type_)
            + toString(this._inputtype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._type_ == child)
        {
            this._type_ = null;
            return;
        }

        if(this._inputtype_ == child)
        {
            this._inputtype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._type_ == oldChild)
        {
            setType((TType) newChild);
            return;
        }

        if(this._inputtype_ == oldChild)
        {
            setInputtype((PInputtype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
