/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class AWhateverHtmlbody extends PHtmlbody
{
    private TWhatever _whatever_;

    public AWhateverHtmlbody()
    {
        // Constructor
    }

    public AWhateverHtmlbody(
        @SuppressWarnings("hiding") TWhatever _whatever_)
    {
        // Constructor
        setWhatever(_whatever_);

    }

    @Override
    public Object clone()
    {
        return new AWhateverHtmlbody(
            cloneNode(this._whatever_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWhateverHtmlbody(this);
    }

    public TWhatever getWhatever()
    {
        return this._whatever_;
    }

    public void setWhatever(TWhatever node)
    {
        if(this._whatever_ != null)
        {
            this._whatever_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._whatever_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._whatever_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._whatever_ == child)
        {
            this._whatever_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._whatever_ == oldChild)
        {
            setWhatever((TWhatever) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
