/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class THtmlTagEnd extends Token
{
    public THtmlTagEnd()
    {
        super.setText("</html>");
    }

    public THtmlTagEnd(int line, int pos)
    {
        super.setText("</html>");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THtmlTagEnd(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHtmlTagEnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THtmlTagEnd text.");
    }
}
