/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TLtSlash extends Token
{
    public TLtSlash()
    {
        super.setText("</");
    }

    public TLtSlash(int line, int pos)
    {
        super.setText("</");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLtSlash(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLtSlash(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLtSlash text.");
    }
}
