/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TPlug extends Token
{
    public TPlug()
    {
        super.setText("plug");
    }

    public TPlug(int line, int pos)
    {
        super.setText("plug");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPlug(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPlug(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPlug text.");
    }
}
