/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TRadio extends Token
{
    public TRadio()
    {
        super.setText("radio");
    }

    public TRadio(int line, int pos)
    {
        super.setText("radio");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRadio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRadio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRadio text.");
    }
}
