/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TSelect extends Token
{
    public TSelect()
    {
        super.setText("select");
    }

    public TSelect(int line, int pos)
    {
        super.setText("select");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSelect(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSelect(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSelect text.");
    }
}
