/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TService extends Token
{
    public TService()
    {
        super.setText("service");
    }

    public TService(int line, int pos)
    {
        super.setText("service");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TService(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTService(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TService text.");
    }
}
