/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TSession extends Token
{
    public TSession()
    {
        super.setText("session");
    }

    public TSession(int line, int pos)
    {
        super.setText("session");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSession(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSession(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSession text.");
    }
}
