/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.node;

import wig.analysis.*;

@SuppressWarnings("nls")
public final class TText extends Token
{
    public TText()
    {
        super.setText("text");
    }

    public TText(int line, int pos)
    {
        super.setText("text");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TText(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTText(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TText text.");
    }
}
