/* This file was generated by SableCC (http://www.sablecc.org/). */

package wig.parser;

import wig.node.*;
import wig.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTService(@SuppressWarnings("unused") TService node)
    {
        this.index = 0;
    }

    @Override
    public void caseTConst(@SuppressWarnings("unused") TConst node)
    {
        this.index = 1;
    }

    @Override
    public void caseTHtml(@SuppressWarnings("unused") THtml node)
    {
        this.index = 2;
    }

    @Override
    public void caseTHtmlTagStart(@SuppressWarnings("unused") THtmlTagStart node)
    {
        this.index = 3;
    }

    @Override
    public void caseTSchema(@SuppressWarnings("unused") TSchema node)
    {
        this.index = 4;
    }

    @Override
    public void caseTSession(@SuppressWarnings("unused") TSession node)
    {
        this.index = 5;
    }

    @Override
    public void caseTShow(@SuppressWarnings("unused") TShow node)
    {
        this.index = 6;
    }

    @Override
    public void caseTExit(@SuppressWarnings("unused") TExit node)
    {
        this.index = 7;
    }

    @Override
    public void caseTReturn(@SuppressWarnings("unused") TReturn node)
    {
        this.index = 8;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 9;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 10;
    }

    @Override
    public void caseTWhile(@SuppressWarnings("unused") TWhile node)
    {
        this.index = 11;
    }

    @Override
    public void caseTPlug(@SuppressWarnings("unused") TPlug node)
    {
        this.index = 12;
    }

    @Override
    public void caseTReceive(@SuppressWarnings("unused") TReceive node)
    {
        this.index = 13;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 14;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 15;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 16;
    }

    @Override
    public void caseTVoid(@SuppressWarnings("unused") TVoid node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTuple(@SuppressWarnings("unused") TTuple node)
    {
        this.index = 18;
    }

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 19;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 20;
    }

    @Override
    public void caseTMeta(@SuppressWarnings("unused") TMeta node)
    {
        this.index = 21;
    }

    @Override
    public void caseTHtmlTagEnd(@SuppressWarnings("unused") THtmlTagEnd node)
    {
        this.index = 22;
    }

    @Override
    public void caseTInput(@SuppressWarnings("unused") TInput node)
    {
        this.index = 23;
    }

    @Override
    public void caseTPosIntconst(@SuppressWarnings("unused") TPosIntconst node)
    {
        this.index = 24;
    }

    @Override
    public void caseTNegIntconst(@SuppressWarnings("unused") TNegIntconst node)
    {
        this.index = 25;
    }

    @Override
    public void caseTSelect(@SuppressWarnings("unused") TSelect node)
    {
        this.index = 26;
    }

    @Override
    public void caseTType(@SuppressWarnings("unused") TType node)
    {
        this.index = 27;
    }

    @Override
    public void caseTName(@SuppressWarnings("unused") TName node)
    {
        this.index = 28;
    }

    @Override
    public void caseTText(@SuppressWarnings("unused") TText node)
    {
        this.index = 29;
    }

    @Override
    public void caseTRadio(@SuppressWarnings("unused") TRadio node)
    {
        this.index = 30;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 31;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 32;
    }

    @Override
    public void caseTAssign(@SuppressWarnings("unused") TAssign node)
    {
        this.index = 33;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 34;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 35;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 36;
    }

    @Override
    public void caseTLtSlash(@SuppressWarnings("unused") TLtSlash node)
    {
        this.index = 37;
    }

    @Override
    public void caseTLtBracket(@SuppressWarnings("unused") TLtBracket node)
    {
        this.index = 38;
    }

    @Override
    public void caseTGtBracket(@SuppressWarnings("unused") TGtBracket node)
    {
        this.index = 39;
    }

    @Override
    public void caseTLPar(@SuppressWarnings("unused") TLPar node)
    {
        this.index = 40;
    }

    @Override
    public void caseTRPar(@SuppressWarnings("unused") TRPar node)
    {
        this.index = 41;
    }

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 42;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 43;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 44;
    }

    @Override
    public void caseTKeep(@SuppressWarnings("unused") TKeep node)
    {
        this.index = 45;
    }

    @Override
    public void caseTRemove(@SuppressWarnings("unused") TRemove node)
    {
        this.index = 46;
    }

    @Override
    public void caseTJoin(@SuppressWarnings("unused") TJoin node)
    {
        this.index = 47;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 48;
    }

    @Override
    public void caseTNeq(@SuppressWarnings("unused") TNeq node)
    {
        this.index = 49;
    }

    @Override
    public void caseTLteq(@SuppressWarnings("unused") TLteq node)
    {
        this.index = 50;
    }

    @Override
    public void caseTGteq(@SuppressWarnings("unused") TGteq node)
    {
        this.index = 51;
    }

    @Override
    public void caseTNot(@SuppressWarnings("unused") TNot node)
    {
        this.index = 52;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 53;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 54;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 55;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 56;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 57;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 58;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 59;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 60;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 61;
    }

    @Override
    public void caseTStringconst(@SuppressWarnings("unused") TStringconst node)
    {
        this.index = 62;
    }

    @Override
    public void caseTWhatever(@SuppressWarnings("unused") TWhatever node)
    {
        this.index = 63;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 64;
    }
}
